<a href="https://colab.research.google.com/github/tvelichkovt/TensorFlow/blob/master/3_TensorFlow_tf_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
    %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

print(tf.__version__, keras.__version__)

In [29]:
# tf.Variable

v = tf.Variable(1213)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1213>


In [40]:
# tf.range

tf.range(1) #[0]
tf.range(2) #[0, 1]
tf.range(3) #[0, 1, 2]
tf.range(4) #[0, 1, 2, 3]

start = 3
limit = 18
delta = 3
tf.range(start, limit, delta)  # [3, 6, 9, 12, 15]

start = 3
limit = 1
delta = -0.5
tf.range(start, limit, delta)  # [3, 2.5, 2, 1.5]

limit = 5
tf.range(limit)  # [0, 1, 2, 3, 4]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [53]:
# tf.range

start = 5
limit = 16
delta = 3
tf.range(start, limit, delta)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5,  8, 11, 14], dtype=int32)>

In [0]:
# add

@tf.function 
def f(x, y): 
  return x + y 

f(1, 2)

In [0]:
# multiply

@tf.function 
def f(x, y): 
  return x ** 2 + y 
x = tf.constant([2]) 
y = tf.constant([3]) 
f(x, y)

In [11]:
# multiply arrays


@tf.function 
def f(x, y): 
  return x ** 2 + y 
x = tf.constant([2, 3]) 
y = tf.constant([3, -2]) 
f(x, y) 


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

In [0]:
# reduce

@tf.function 
def f(x): 
  if tf.reduce_sum(x) > 0: 
    return x * x 
  else: 
    return -x // 2 
f(tf.constant(-13))

In [0]:
# tf.Tensor and tf.Variable objects:

@tf.function 
def f(): 
  return x ** 2 + y 
x = tf.constant([-2, -3]) 
y = tf.Variable([3, -2]) 
f() 


In [57]:
 # tf.print, tf.Variable and others:

v = tf.Variable(1) 
@tf.function 
def f(x): 
  for i in tf.range(x): 
    v.assign_add(i) 
f(4)
v


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>

In [58]:
tf.range(4)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>