<a href="https://colab.research.google.com/github/tvelichkovt/TensorFlow/blob/master/TF_002_Eager_Mode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# tf -> "import"

In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
    %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print('TensorFlow ver is:', tf.__version__, '\nKeras ver is:', keras.__version__, '\nPandas ver is:', pd.__version__, '\nNumpy ver is:', np.__version__)

TensorFlow ver is: 2.2.0 
Keras ver is: 2.3.0-tf 
Pandas ver is: 1.0.5 
Numpy ver is: 1.18.5


# tf -> "eager mode"

In [3]:
x = tf.constant([[1.,2.,3.],[4.,5.,6.],[7,8,9]])
print(x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)


In [4]:
print(type(x))
print(x.dtype)
print(x.shape)

<class 'tensorflow.python.framework.ops.EagerTensor'>
<dtype: 'float32'>
(3, 3)


In [5]:
y = tf.matmul(x,x)
print(y)

tf.Tensor(
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]], shape=(3, 3), dtype=float32)


# tf -> "NumPy operations"

In [6]:
ndarray = np.ones([3, 3])

# convert numpy arrays to Tensors automatically
tensor = tf.multiply(ndarray, 42)
print(tensor)
print(type(tensor))

# convert Tensors to numpy arrays 
print(np.add(tensor, 1))

#.numpy() method explicitly converts a Tensor to a numpy array
print(tensor.numpy())

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


# tf -> "tf.placeholder" in TensorFlow 1.x code

In [7]:
placeholder = tf.placeholder(shape = [3, 3], dtype = tf.float32)

AttributeError: ignored

In [8]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [9]:
placeholder = tf.placeholder(shape = [3, 3], dtype = tf.float32)