<a href="https://colab.research.google.com/github/tvelichkovt/TensorFlow/blob/master/TF_000_Concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# tf -> "import"

In [62]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
    %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print('TensorFlow ver is:', tf.__version__, '\nKeras ver is:', keras.__version__, '\nPandas ver is:', pd.__version__, '\nNumpy ver is:', np.__version__)

TensorFlow ver is: 2.2.0 
Keras ver is: 2.3.0-tf 
Pandas ver is: 1.0.5 
Numpy ver is: 1.18.5


# tf -> "def"

In [63]:
def f(x):
  return 2 * x + 1

f(5)

11

# tf -> "tf.nn.relu" with linear function


In [64]:
def f(n):
  return x + 1

@tf.function
def deep_net(n):
  return tf.nn.relu(f(n))

#deep_net(tf.constant((1, 2, 3)))

# tf -> "timeit"

In [65]:
import timeit
conv_layer = tf.keras.layers.Conv2D(100, 3)

@tf.function
def conv_fn(image):
  return conv_layer(image)

image = tf.zeros([1, 200, 200, 100])
# warm up
conv_layer(image); conv_fn(image)
print("Eager conv:", timeit.timeit(lambda: conv_layer(image), number=10))
print("Function conv:", timeit.timeit(lambda: conv_fn(image), number=10))
print("Note how there's not much difference in performance for convolutions")


Eager conv: 1.3156690089999756
Function conv: 1.2561590679997607
Note how there's not much difference in performance for convolutions


# tf -> "@tf.function"

In [66]:
@tf.function
def square_if_positive(x):
  if x > 0:
    x = x * x
  else:
    x = 0
  return x


print('square_if_positive(2) = {}'.format(square_if_positive(tf.constant(2))))
print('square_if_positive(-2) = {}'.format(square_if_positive(tf.constant(-2))))

square_if_positive(2) = 4
square_if_positive(-2) = 0


In [67]:
@tf.function
def sum_even(items):
  s = 0
  for c in items:
    if c % 2 > 0:
      continue
    s += c
  return s


sum_even(tf.constant([10, 12, 15, 20]))

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [68]:
@tf.function
def fizzbuzz(n):
  for i in tf.range(n):
    if i % 3 == 0:
      tf.print('Fizz')
    elif i % 5 == 0:
      tf.print('Buzz')
    else:
      tf.print(i)

fizzbuzz(tf.constant(15))

Fizz
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14


In [69]:
class CustomModel(tf.keras.models.Model):

  @tf.function
  def call(self, input_data):
    if tf.reduce_mean(input_data) > 0:
      return input_data
    else:
      return input_data // 2


model = CustomModel()

model(tf.constant([-2, -4]))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>

In [70]:
v = tf.Variable(5)

@tf.function
def find_next_odd():
  v.assign(v + 1)
  if v % 2 == 0:
    v.assign(v + 1)


find_next_odd()
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>

# tf -> "tf.Variable"

In [71]:
# tf.Variable

v = tf.Variable(1213)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1213>


# tf -> "tf.range"


In [72]:
tf.range(1) #[0]
tf.range(2) #[0, 1]
tf.range(3) #[0, 1, 2]
tf.range(4) #[0, 1, 2, 3]

start = 3
limit = 18
delta = 3
tf.range(start, limit, delta)  # [3, 6, 9, 12, 15]

start = 3
limit = 1
delta = -0.5
tf.range(start, limit, delta)  # [3, 2.5, 2, 1.5]

limit = 5
tf.range(limit)  # [0, 1, 2, 3, 4]

start = 5
limit = 16
delta = 3
tf.range(start, limit, delta)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5,  8, 11, 14], dtype=int32)>

# tf -> "add"


In [73]:
@tf.function 
def f(x, y): 
  return x + y 

f(1, 2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

# tf -> "multiply"

In [74]:
@tf.function 
def f(x, y): 
  return x ** 2 + y 
x = tf.constant([2]) 
y = tf.constant([3]) 
f(x, y)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([7], dtype=int32)>

# tf -> "multiply arrays"

In [75]:
@tf.function 
def f(x, y): 
  return x ** 2 + y 
x = tf.constant([2, 3]) 
y = tf.constant([3, -2]) 
f(x, y) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

# tf -> "reduce"

In [76]:
@tf.function 
def f(x): 
  if tf.reduce_sum(x) > 0: 
    return x * x 
  else: 
    return -x // 2 
f(tf.constant(-13))

<tf.Tensor: shape=(), dtype=int32, numpy=6>

# tf -> "tf.constant" + "tf.Variable"

In [77]:
@tf.function 
def f(): 
  return x ** 2 + y 
x = tf.constant([-2, -3]) 
y = tf.Variable([3, -2]) 
f() 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

# tf -> "tf.print" + "tf.Variable" + "others"

In [78]:
v = tf.Variable(1) 
@tf.function 
def f(x): 
  for i in tf.range(x): 
    v.assign_add(i) 
f(4)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>

# tf -> "TensorArray"


In [79]:
@tf.function 
def f(x): 
  ta = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=True) 
  for i in range(len(x)): 
    ta = ta.write(i, x[i] + 1) 
  return ta.stack() 
f(tf.constant([1, 2, 3])) 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

# tf -> "Passing python scalars or lists as arguments to tf.function"

In [80]:
@tf.function 
def f(x): 
  return tf.abs(x) 
f1 = f.get_concrete_function(1) 
f2 = f.get_concrete_function(2)  # Slow - builds new graph 
f1 is f2 # False

f1 = f.get_concrete_function(tf.constant(1)) 
f2 = f.get_concrete_function(tf.constant(2))  # Fast - reuses f1 
f1 is f2 # True

True

# tf -> "two separate graphs, each specialized to a different shape"

In [81]:
@tf.function 
def f(x): 
  return x + 1 
vector = tf.constant([1.0, 1.0]) 
matrix = tf.constant([[3.0]]) 
f.get_concrete_function(vector) is f.get_concrete_function(matrix) 

False

# tf -> "avoid creating multiple graphs when Tensors have dynamic shapes"

In [82]:
@tf.function( 
    input_signature=[tf.TensorSpec(shape=None, dtype=tf.float32)]) 
def f(x): 
  return x + 1 
vector = tf.constant([1.0, 1.0]) 
matrix = tf.constant([[3.0]]) 
f.get_concrete_function(vector) is f.get_concrete_function(matrix) 

True

# tf -> "Variables may only be created once! tf.function only allows creating new tf.Variable objects when it is called for the first time"

In [83]:
class MyModule(tf.Module): 
  def __init__(self): 
    self.v = None 
 
  @tf.function 
  def call(self, x): 
    if self.v is None: 
      self.v = tf.Variable(tf.ones_like(x)) 
    return self.v * x 

# tf -> "print"

In [84]:
@tf.function
def f():
    tensor = tf.range(10)
    tf.print(tensor, output_stream=sys.stderr)
    return tensor

range_tensor = f()

[0 1 2 ... 7 8 9]


In [85]:
tensor_a = tf.range(2)
tensor_b = tensor_a * 2
tf.print(tensor_a, tensor_b)

[0 1] [0 2]
